package com.simibubi.create.foundation.config;

import com.simibubi.create.foundation.config.util.Validatable;
import me.shedaniel.autoconfig.ConfigData;
import me.shedaniel.autoconfig.annotation.ConfigEntry.Gui.Tooltip;
import net.minecraft.util.math.MathHelper;

public class CKinetics implements Validatable {
	@Tooltip
	boolean disableStress = false; // "Disable the Stress mechanic altogether."
	@Tooltip
	int maxBeltLength = 20; // min 5, "Maximum length in blocks of mechanical belts."
	@Tooltip
	int crushingDamage = 4; // min 0, "Damage dealt by active Crushing Wheels."
	@Tooltip
	int maxMotorSpeed = 256; // min 64, "[in Revolutions per Minute]" "Maximum allowed speed of a configurable motor."
	@Tooltip
	int waterWheelBaseSpeed = 4; // min 1, "[in Revolutions per Minute]" "Added rotation speed by a water wheel when at least one flow is present."
	@Tooltip
	int waterWheelFlowSpeed = 4; // min 1, "[in Revolutions per Minute]" "Rotation speed gained by a water wheel for each side with running fluids. (halved if not against blades)"
	@Tooltip
	int furnaceEngineSpeed = 16; // min 1, "[in Revolutions per Minute]" "Base rotation speed for the furnace engine generator"
	@Tooltip
	int maxRotationSpeed = 256; // min 64, "[in Revolutions per Minute]" "Maximum allowed rotation speed for any Kinetic Tile."
	@Tooltip
	DeployerAggroSetting ignoreDeployerAttacks = DeployerAggroSetting.CREEPERS; // "Select what mobs should ignore Deployers when attacked by them."
	@Tooltip
	int kineticValidationFrequency = 60; // min 5, "Game ticks between Kinetic Blocks checking whether their source is still valid."
	@Tooltip
	float crankHungerMultiplier = 0.01f; // min 0, max 1, "multiplier used for calculating exhaustion from speed when a crank is turned."

	@Tooltip
	int fanPushDistance = 20; // min 5, "Maximum distance in blocks Fans can push entities."
	@Tooltip
	int fanPullDistance = 20; // min 5, "Maximum distance in blocks from where Fans can pull entities."
	@Tooltip
	int fanBlockCheckRate = 30; // min 10, "Game ticks between Fans checking for anything blocking their air flow."
	@Tooltip
	int fanRotationArgmax = 256; // min 64, "[in Revolutions per Minute]" "Rotation speed at which the maximum stats of fans are reached."
	@Tooltip
	int generatingFanSpeed = 4; // min 0, "[in Revolutions per Minute]" "Rotation speed generated by a vertical fan above fire."
	@Tooltip
	int inWorldProcessingTime = 150; // min 0, "Game ticks required for a Fan-based processing recipe to take effect."

	@Tooltip
	int maxBlocksMoved = 2048; // min 1, "Maximum amount of blocks in a structure movable by Pistons, Bearings or other means."
	@Tooltip
	int maxChassisRange = 16; // min 1, "Maximum value of a chassis attachment range."
	@Tooltip
	int maxPistonPoles = 64; // min 1, "Maximum amount of extension poles behind a Mechanical Piston."
	@Tooltip
	int maxRopeLength = 128; // min 1, "Max length of rope available off a Rope Pulley."
	@Tooltip
	int maxCartCouplingLength = 32; // min 1, "Maximum allowed distance of two coupled minecarts."

	@Tooltip
	float mediumSpeed = 30f; // min 0, max 4096, "[in Revolutions per Minute]" "Minimum speed of rotation to be considered 'medium'"
	@Tooltip
	float fastSpeed = 100f;// min 0, max 65535, "[in Revolutions per Minute]" "Minimum speed of rotation to be considered 'fast'"
	@Tooltip
	float mediumStressImpact = 4f;// min 0, max 4096, "[in Stress Units]" "Minimum stress impact to be considered 'medium'"
	@Tooltip
	float highStressImpact = 8f;// min 0, max 65535, "[in Stress Units]" "Minimum stress impact to be considered 'high'"
	@Tooltip
	float mediumCapacity = 128f;// min 0, max 4096, "[in Stress Units]" "Minimum added Capacity by sources to be considered 'medium'"
	@Tooltip
	float highCapacity = 512f;// min 0, max 65535, "[in Stress Units]" "Minimum added Capacity by sources to be considered 'high'"

	@Override
	public void validate() throws ConfigData.ValidationException {
		maxBeltLength = Math.max(maxBeltLength, 5);
		crushingDamage = Math.max(crushingDamage, 0);
		maxMotorSpeed = Math.max(maxMotorSpeed, 64);
		waterWheelBaseSpeed = Math.max(waterWheelBaseSpeed, 1);
		waterWheelFlowSpeed = Math.max(waterWheelFlowSpeed, 1);
		furnaceEngineSpeed = Math.max(furnaceEngineSpeed, 1);
		maxRotationSpeed = Math.max(maxRotationSpeed, 64);
		kineticValidationFrequency = Math.max(kineticValidationFrequency, 5);
		crankHungerMultiplier = MathHelper.clamp(crankHungerMultiplier, 0, 1);
		fanPushDistance = Math.max(fanPushDistance, 5);
		fanPullDistance = Math.max(fanPullDistance, 5);
		fanBlockCheckRate = Math.max(fanBlockCheckRate, 10);
		fanRotationArgmax = Math.max(fanRotationArgmax, 64);
		generatingFanSpeed = Math.max(generatingFanSpeed, 0);
		inWorldProcessingTime = Math.max(inWorldProcessingTime, 0);
		maxBlocksMoved = Math.max(maxBlocksMoved, 1);
		maxChassisRange = Math.max(maxChassisRange, 1);
		maxPistonPoles = Math.max(maxPistonPoles, 1);
		maxRopeLength = Math.max(maxRopeLength, 1);
		maxCartCouplingLength = Math.max(maxCartCouplingLength, 1);
		mediumSpeed = MathHelper.clamp(mediumSpeed, 0f, 4096f);
		fastSpeed = MathHelper.clamp(fastSpeed, 0f, 65535f);
		mediumStressImpact = MathHelper.clamp(mediumStressImpact, 0f, 4096f);
		highStressImpact = MathHelper.clamp(highStressImpact, 0f, 65535f);
		mediumCapacity = MathHelper.clamp(mediumCapacity, 0f, 4096f);
		highCapacity = MathHelper.clamp(highCapacity, 0f, 65535f);
	}

	/*
		static String stats = "Configure speed/capacity levels for requirements and indicators.";
		static String rpm = "[in Revolutions per Minute]";
		static String su = "[in Stress Units]";
		static String stress = "Fine tune the kinetic stats of individual components";
	 */

	public enum DeployerAggroSetting {
		ALL, CREEPERS, NONE
	}
}
