package com.simibubi.create.foundation.config;

import me.shedaniel.autoconfig.annotation.ConfigEntry;

public class CKinetics {
	public enum DeployerAggroSetting { ALL, CREEPERS, NONE }
	boolean disableStress = false; // "Disable the Stress mechanic altogether."
	static int maxBeltLength = 20; // min 5, "Maximum length in blocks of mechanical belts."
	static int crushingDamage = 4; // min 0, "Damage dealt by active Crushing Wheels."
	static int maxMotorSpeed = 256; // min 64, "[in Revolutions per Minute]" "Maximum allowed speed of a configurable motor."
	static int waterWheelBaseSpeed = 4; // min 1, "[in Revolutions per Minute]" "Added rotation speed by a water wheel when at least one flow is present."
	static int waterWheelFlowSpeed = 4; // min 1, "[in Revolutions per Minute]" "Rotation speed gained by a water wheel for each side with running fluids. (halved if not against blades)"
	static int furnaceEngineSpeed = 16; // min 1, "[in Revolutions per Minute]" "Base rotation speed for the furnace engine generator"
	static int maxRotationSpeed = 256; // min 64, "[in Revolutions per Minute]" "Maximum allowed rotation speed for any Kinetic Tile."
	DeployerAggroSetting ignoreDeployerAttacks = DeployerAggroSetting.CREEPERS; // "Select what mobs should ignore Deployers when attacked by them."
	static int kineticValidationFrequency = 60; // min 5, "Game ticks between Kinetic Blocks checking whether their source is still valid."
	static float crankHungerMultiplier = 0.01f; // min 0, max 1, "multiplier used for calculating exhaustion from speed when a crank is turned."
	// fan configs        public ConfigGroup fan = group(1, "encasedFan", "Encased Fan");
	@ConfigEntry.Gui.PrefixText()
	static int fanPushDistance = 20; // min 5, "Maximum distance in blocks Fans can push entities."
	static int fanPullDistance = 20; // min 5, "Maximum distance in blocks from where Fans can pull entities."
	static int fanBlockCheckRate = 30; // min 10, "Game ticks between Fans checking for anything blocking their air flow."
	static int fanRotationArgmax = 256; // min 64, "[in Revolutions per Minute]" "Rotation speed at which the maximum stats of fans are reached."
	static int generatingFanSpeed = 4; // min 0, "[in Revolutions per Minute]" "Rotation speed generated by a vertical fan above fire."
	static int inWorldProcessingTime = 150; // min 0, "Game ticks required for a Fan-based processing recipe to take effect."
	// contraptions        public ConfigGroup contraptions = group(1, "contraptions", "Moving Contraptions");
	@ConfigEntry.Gui.PrefixText()
	static int maxBlocksMoved = 2048; // min 1, "Maximum amount of blocks in a structure movable by Pistons, Bearings or other means."
	static int maxChassisRange = 16; // min 1, "Maximum value of a chassis attachment range."
	static int maxPistonPoles = 64; // min 1, "Maximum amount of extension poles behind a Mechanical Piston."
	static int maxRopeLength = 128; // min 1, "Max length of rope available off a Rope Pulley."
	static int maxCartCouplingLength = 32; // min 1, "Maximum allowed distance of two coupled minecarts."

	// stats            public ConfigGroup state = group(1, "stats", Comments.stats);
	@ConfigEntry.Gui.PrefixText()
	static float mediumSpeed = 30f; // min 0, max 4096, "[in Revolutions per Minute]" "Minimum speed of rotation to be considered 'medium'"
	static float fastSpeed = 100f;// min 0, max 65535, "[in Revolutions per Minute]" "Minimum speed of rotation to be considered 'fast'"
	static float mediumStressImpact = 4f;// min 0, max 4096, "[in Stress Units]" "Minimum stress impact to be considered 'medium'"
	static float highStressImpact = 8f;// min 0, max 65535, "[in Stress Units]" "Minimum stress impact to be considered 'high'"
	static float mediumCapacity = 128f;// min 0, max 4096, "[in Stress Units]" "Minimum added Capacity by sources to be considered 'medium'"
	static float highCapacity = 512f;// min 0, max 65535, "[in Stress Units]" "Minimum added Capacity by sources to be considered 'high'"
	/*
		static String stats = "Configure speed/capacity levels for requirements and indicators.";
		static String rpm = "[in Revolutions per Minute]";
		static String su = "[in Stress Units]";
		static String stress = "Fine tune the kinetic stats of individual components";
	 */
}
